Implement adding arrow object
FaaSr/FaaSr-package pull request #35
Opened 2023-10-17 13:57 UTC by Yun-Jung

This file is fed with Logging Server and creates the arrow object by credential provided by json file.

2023-10-17 19:29 UTC, spark0510 requested changes

2023-10-17 19:29 UTC, spark0510 commented on R/faasr_arrow_s3_bucket.R
> +faasr_arrow_s3_bucket <- function(server_name=.faasr$LoggingServer) {
Set no default value for the argument "server_name"
`server_name=.faasr$LoggingServer` -> `server_name`

2023-10-19 16:03 UTC, renatof commented
Thanks folks. Sorry for the change of mind, but now I am leaning towards the original goal of allowing using a default server. I guess my main issue is that we're effectively electing the LoggingServer as default, and that may not be intuitive to the user that "Logging" means "Default"
One possibility to make that more clear and explicit would be to change the JSON key "LoggingServer" to "DefaultDataServer" to make it more explicit, and then allow that to be the default for S3 put/get and arrow. We can discuss that before making a change

2023-10-19 16:21 UTC, renatof commented
actually, DefaultDataStore to be consistent with DataStores

2023-10-20 19:31 UTC, closed without merging

2023-10-20 19:31 UTC, renatof commented
closing as it this been addressed in a different pull request. thanks Yun-Jung, Sungjae!