update lambda part in client tool
FaaSr/FaaSr-package pull request #55
Opened 2024-01-31 03:01 UTC by nanmu08

update lambda part in client tool, replace aws cli with paws lib, also update lambda part in faasr trigger file.

2024-02-01 14:06 UTC, spark0510 requested changes
Here's some comments with the procedure.

1. For whom use our default FaaSr container, they don't really need their own ECR. So I suggest to only create the repository when they provide their own image from other than ECR. (If they provide the image with their own ECR, we don't need to create one for them as they already have it)
2. I found that repository name is the image uri. e.g., if the repository name is "FaaSr", then the image url will be "<my_id>.dkr.ecr.<region>.amazonaws.com/**FaaSr**". 
So, I suggest to set the repository name with the user provided name. e.g., if user gives us "spark0510/test" for their image name from docker, we can build the repository with the name "<my_id>.dkr.ecr.<region>.amazonaws.com/**test**", instead of asking users to provide the repository name i.e., "lambda-script"
3. I suggest to just create the role name "faasr_role" and explictly use in our FaaSr Lambda functions, instead of asking users to provide the role name. i.e. faasr-lambda
4. I can see "sts()" functions many times, however, it seems like it's only for the account_id. I suggest to use only once in the "faasr_register_workflow_aws_lambda" on the corresponding lambda account. As a result, it will reduce the amount of transactions.

2024-02-01 14:06 UTC, spark0510 commented on R/faasr_client_api_aws-lambda.R
> +      aws_region <- faasr$ComputeServers[[faas]]$Region
I guess "aws_region" will be overwritten, if there are more than 2 Lambda Servers which are using different Region.

2024-02-01 14:06 UTC, spark0510 commented on R/faasr_client_api_aws-lambda.R
>      return(FALSE)
Please make it retrun "" instead of FALSE

2024-02-01 14:06 UTC, spark0510 commented on R/faasr_client_api_aws-lambda.R
> +          secret_access_key=cred$lambda_a_SECRET_KEY,
"lambda_a_" is not defined.

2024-02-01 14:06 UTC, spark0510 commented on R/faasr_client_api_aws-lambda.R
> +          secret_access_key=cred$lambda_a_SECRET_KEY,
Every functions for paws is using "lambda_a_" in their creds, so it needs to be modified.

2024-02-01 14:06 UTC, spark0510 commented on R/faasr_client_api_aws-lambda.R
> +    writeLines(faasr_json, paste0("payload_ld_",rd_nb,".json"))
We don't need to create the "payload.json" file anymore.
line no.666, 668, and 669 will be unnecessary
line no.682 as well.

2024-02-01 14:53 UTC, spark0510 commented on R/faasr_client_api_aws-lambda.R
> +    writeLines(faasr_json, paste0("payload_ld_",rd_nb,".json"))
not 666.

2024-02-08 03:55 UTC, nanmu08 commented on R/faasr_client_api_aws-lambda.R
> +      aws_region <- faasr$ComputeServers[[faas]]$Region
Has updated

2024-02-08 03:56 UTC, nanmu08 commented on R/faasr_client_api_aws-lambda.R
>      return(FALSE)
has updated

2024-02-08 03:56 UTC, nanmu08 commented on R/faasr_client_api_aws-lambda.R
> +          secret_access_key=cred$lambda_a_SECRET_KEY,
has updated

2024-02-08 03:58 UTC, nanmu08 commented
Updated lambda register process. remove Image build, support create lambda function in multiple region.

2024-02-08 16:13 UTC, spark0510 commented
Tested with forcast example: working fine.

2024-02-08 16:13 UTC, merged